#!/usr/bin/env bash
# Build ClaudeBar from source on your Mac.
#
# The Xcode project is generated by Tuist and is git-ignored, so every fresh
# clone (and every sync that touches Project.swift or Tuist/Package.swift)
# needs a regenerate before it will build. This script does that for you.
#
# Usage:
#   ./scripts/dev-build.sh                # generate + Debug build (fast sanity check)
#   ./scripts/dev-build.sh --open         # generate + open the workspace in Xcode
#   ./scripts/dev-build.sh --test         # generate + run the test suite
#   ./scripts/dev-build.sh --release      # generate + Release build
#   ./scripts/dev-build.sh --install      # archive + install to /Applications
#   ./scripts/dev-build.sh --zip          # archive -> .build/ClaudeBar-<version>.zip
#   ./scripts/dev-build.sh --stage        # archive -> signed .build/ClaudeBar.app, no zip
#   ./scripts/dev-build.sh --clean        # nuke generated project + derived data first
#
# Flags combine, e.g.: ./scripts/dev-build.sh --clean --test
#   --skip-generate  reuse an existing workspace (saves ~30s on repeat runs)
#   --universal      archive for arm64 + x86_64 instead of this Mac's arch
#
# Environment overrides (set by scripts/fork-release.sh; ignore for local work):
#   CLAUDEBAR_VERSION        version to stamp instead of <upstream>-fork.<sha>
#   CLAUDEBAR_SIGN_IDENTITY  codesign identity instead of "-" (ad-hoc). A real
#                            Developer ID also turns on the hardened runtime and
#                            a secure timestamp, both preconditions for notarizing.
#
# --install, --zip and --stage archive rather than plain-build, which is what
# strips the SwiftUI preview scaffolding out of the bundle. None of them need the
# Xcode GUI, but all need Xcode.app installed for the toolchain.

set -euo pipefail

ACTION="build"
CONFIG="Debug"
CLEAN="no"
GENERATE="yes"
UNIVERSAL="no"

while [ $# -gt 0 ]; do
    case "$1" in
        --open)          ACTION="open"; shift ;;
        --test)          ACTION="test"; shift ;;
        --install)       ACTION="install"; CONFIG="Release"; shift ;;
        --zip)           ACTION="zip"; CONFIG="Release"; shift ;;
        --stage)         ACTION="stage"; CONFIG="Release"; shift ;;
        --release)       CONFIG="Release"; shift ;;
        --debug)         CONFIG="Debug"; shift ;;
        --clean)         CLEAN="yes"; shift ;;
        --skip-generate) GENERATE="no"; shift ;;
        --universal)     UNIVERSAL="yes"; shift ;;
        -h|--help)       sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *)               echo "Unknown option: $1" >&2; exit 2 ;;
    esac
done

cd "$(git rev-parse --show-toplevel)"

info() { printf '\033[1;34m==>\033[0m %s\n' "$1"; }
die()  { printf '\033[1;31mxx\033[0m  %s\n' "$1" >&2; exit 1; }

[ "$(uname -s)" = "Darwin" ] || die "ClaudeBar is a macOS app; this script needs a Mac."
command -v tuist >/dev/null 2>&1 || die "Tuist not found. Install it with: brew install --cask tuist"
command -v xcodebuild >/dev/null 2>&1 || die "xcodebuild not found. Install Xcode from the App Store."

# The Command Line Tools alone are not enough: this project needs a real Xcode
# for the macOS SDK, the Swift macro toolchain, and `xcodebuild archive`.
# You never have to *open* Xcode — but it has to be installed and selected.
SDK_ROOT="$(xcode-select -p 2>/dev/null || true)"
case "$SDK_ROOT" in
    *Xcode*) : ;;
    *) die "xcode-select points at '${SDK_ROOT:-nothing}', not an Xcode.app.
    Install Xcode, then point the toolchain at it:
        xcodes install --latest        # or: mas install 497799835
        sudo xcode-select -s /Applications/Xcode.app
        sudo xcodebuild -license accept" ;;
esac

DERIVED="$PWD/.build/derived"
WORKSPACE="ClaudeBar.xcworkspace"
ARCH="$(uname -m)"
DEST="platform=macOS,arch=$ARCH"
ENTITLEMENTS="Sources/App/entitlements.plist"

# --- Generate ---------------------------------------------------------------

if [ "$CLEAN" = "yes" ]; then
    info "Cleaning generated project and derived data"
    rm -rf "$DERIVED" ClaudeBar.xcodeproj ClaudeBar.xcworkspace Derived
    tuist clean >/dev/null 2>&1 || true
fi

if [ "$GENERATE" = "yes" ] || [ ! -d "$WORKSPACE" ]; then
    info "Resolving dependencies (tuist install)"
    tuist install

    info "Generating Xcode project (tuist generate)"
    tuist generate --no-open

    # Workaround for tuist/tuist#9111 — CI runs this too; without it the build
    # fails with "Unexpected duplicate tasks" on SwiftTerm's Shaders.metal.
    ./scripts/fix-swiftterm-metal.sh
else
    info "Reusing existing $WORKSPACE (--skip-generate)"
fi

if [ "$ACTION" = "open" ]; then
    info "Opening $WORKSPACE"
    open "$WORKSPACE"
    exit 0
fi

# --- Test -------------------------------------------------------------------

if [ "$ACTION" = "test" ]; then
    info "Running tests"
    xcodebuild test \
        -scheme ClaudeBar \
        -workspace "$WORKSPACE" \
        -destination "$DEST" \
        -derivedDataPath "$DERIVED" \
        -skipMacroValidation
    exit 0
fi

# --- Build ------------------------------------------------------------------

if [ "$ACTION" = "build" ]; then
    # Plain build — fast verification. The bundle it leaves in DerivedData is
    # fine to run from Xcode but is not a distributable app (see below).
    info "Building $CONFIG"
    xcodebuild build \
        -scheme ClaudeBar \
        -workspace "$WORKSPACE" \
        -destination "$DEST" \
        -derivedDataPath "$DERIVED" \
        -skipMacroValidation \
        -configuration "$CONFIG"

    APP="$DERIVED/Build/Products/$CONFIG/ClaudeBar.app"
    [ -d "$APP" ] || die "Build reported success but $APP is missing."
    info "Built $APP"
    exit 0
fi

# --- Archive (install / zip) ------------------------------------------------

# `xcodebuild build` is NOT good enough for something you install. The app
# target sets ENABLE_DEBUG_DYLIB=YES for SwiftUI previews, so an ordinary build
# splits the binary and leaves a ClaudeBar.debug.dylib inside the bundle. An
# archive build is an install-action build, which drops the preview scaffolding
# and produces the same single-binary bundle upstream ships. Mirrors the
# `xcodebuild archive` invocation in .github/workflows/release.yml.

ARCHIVE="$PWD/.build/ClaudeBar.xcarchive"
rm -rf "$ARCHIVE"

if [ "$UNIVERSAL" = "yes" ]; then
    ARCHS_ARG='arm64 x86_64'
    info "Archiving Release (universal: arm64 + x86_64)"
else
    ARCHS_ARG="$ARCH"
    info "Archiving Release ($ARCH)"
fi

xcodebuild archive \
    -scheme ClaudeBar \
    -workspace "$WORKSPACE" \
    -configuration Release \
    -archivePath "$ARCHIVE" \
    -destination 'generic/platform=macOS' \
    -derivedDataPath "$DERIVED" \
    -skipMacroValidation \
    ARCHS="$ARCHS_ARG" \
    ONLY_ACTIVE_ARCH=NO \
    CODE_SIGN_IDENTITY="-" \
    CODE_SIGNING_REQUIRED=NO \
    CODE_SIGNING_ALLOWED=NO

STAGED="$PWD/.build/ClaudeBar.app"
rm -rf "$STAGED"
cp -R "$ARCHIVE/Products/Applications/ClaudeBar.app" "$STAGED"
APP="$STAGED"

if [ -e "$APP/Contents/Frameworks/ClaudeBar.debug.dylib" ]; then
    die "Archive still contains the preview debug dylib — that shouldn't happen."
fi

# --- Stamp ------------------------------------------------------------------

# Stamp the bundle (not the repo) so your build is identifiable and so Sparkle
# doesn't quietly replace it with an official tddworks release. Patching the
# built .app instead of Sources/App/Info.plist keeps your diff against upstream
# empty here — Info.plist is rewritten on every upstream release.
#
# A release build overrides the stamp with CLAUDEBAR_VERSION: a cask's `version`
# has to match a published tag, and "-fork.<sha>" changes on every commit.
UPSTREAM_VERSION="$(sed -n 's/^## \[\([0-9][^]]*\)\].*/\1/p' CHANGELOG.md | head -1)"
SHA="$(git rev-parse --short HEAD)"
STAMP="${CLAUDEBAR_VERSION:-${UPSTREAM_VERSION:-0.0.0}-fork.$SHA}"
PLIST="$APP/Contents/Info.plist"

/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $STAMP" "$PLIST"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(git rev-list --count HEAD)" "$PLIST"
/usr/libexec/PlistBuddy -c "Set :SUEnableAutomaticChecks false" "$PLIST" 2>/dev/null || true

# Sign. The archive was built with CODE_SIGNING_ALLOWED=NO, and editing
# Info.plist would invalidate a signature anyway. Nested code first, then the
# top level with entitlements — --deep would otherwise stamp the app's
# entitlements onto every embedded framework.
#
# Ad-hoc is the default and is all a local build needs. A release run passes a
# Developer ID through CLAUDEBAR_SIGN_IDENTITY, which additionally needs the
# hardened runtime and a secure timestamp — notarization rejects a submission
# missing either, and an ad-hoc signature can carry neither.
IDENTITY="${CLAUDEBAR_SIGN_IDENTITY:--}"

if [ "$IDENTITY" = "-" ]; then
    info "Signing ad-hoc"
    codesign --force --deep --sign - "$APP" >/dev/null 2>&1
    codesign --force --sign - --entitlements "$ENTITLEMENTS" "$APP" >/dev/null 2>&1
else
    info "Signing with: $IDENTITY"
    codesign --force --deep --options runtime --timestamp --sign "$IDENTITY" "$APP"
    codesign --force --options runtime --timestamp \
        --entitlements "$ENTITLEMENTS" --sign "$IDENTITY" "$APP"
fi

codesign --verify --strict "$APP" || die "Signing failed verification."

# --- Stage ------------------------------------------------------------------

# Stop with a signed bundle on disk. scripts/fork-release.sh uses this so it can
# notarize and staple the .app *before* archiving it — stapling rewrites the
# bundle, so a zip made beforehand would not contain the ticket.
if [ "$ACTION" = "stage" ]; then
    info "Staged $APP"
    echo "    version:  $STAMP"
    exit 0
fi

# --- Zip --------------------------------------------------------------------

if [ "$ACTION" = "zip" ]; then
    ZIP="$PWD/.build/ClaudeBar-$STAMP.zip"
    rm -f "$ZIP"
    # ditto --sequesterRsrc --keepParent is the archiver Apple expects for
    # .app bundles; plain `zip` loses symlinks and breaks the signature.
    ditto -c -k --sequesterRsrc --keepParent "$APP" "$ZIP"
    info "Wrote $ZIP"
    echo "    version:  $STAMP"
    echo "    sha256:   $(shasum -a 256 "$ZIP" | cut -d' ' -f1)"
    echo "    size:     $(du -h "$ZIP" | cut -f1)"
    exit 0
fi

# --- Install ----------------------------------------------------------------

if [ -d /Applications/ClaudeBar.app ] && [ ! -w /Applications/ClaudeBar.app ]; then
    die "/Applications/ClaudeBar.app isn't writable by you — it was probably
    installed by Homebrew. Remove it first:  brew uninstall --cask claudebar"
fi

if pgrep -x ClaudeBar >/dev/null 2>&1; then
    info "Quitting the running ClaudeBar"
    osascript -e 'quit app "ClaudeBar"' 2>/dev/null || pkill -x ClaudeBar || true
    sleep 2
fi

info "Installing to /Applications/ClaudeBar.app ($STAMP)"
rm -rf /Applications/ClaudeBar.app
ditto "$APP" /Applications/ClaudeBar.app
xattr -dr com.apple.quarantine /Applications/ClaudeBar.app 2>/dev/null || true

open -a /Applications/ClaudeBar.app
info "Installed and launched — look for the icon in your menu bar."
echo "    version:  $STAMP"
echo "    settings: ~/.claudebar/settings.json"
echo "    logs:     ~/Library/Logs/ClaudeBar/ClaudeBar.log"
