#!/usr/bin/env bash
# Build ClaudeBar from source on your Mac.
#
# The Xcode project is generated by Tuist and is git-ignored, so every fresh
# clone (and every sync that touches Project.swift or Tuist/Package.swift)
# needs a regenerate before it will build. This script does that for you.
#
# Usage:
#   ./scripts/dev-build.sh                # generate + Debug build (fast sanity check)
#   ./scripts/dev-build.sh --open         # generate + open the workspace in Xcode
#   ./scripts/dev-build.sh --test         # generate + run the test suite
#   ./scripts/dev-build.sh --release      # generate + Release build
#   ./scripts/dev-build.sh --install      # Release build -> /Applications/ClaudeBar.app
#   ./scripts/dev-build.sh --clean        # nuke generated project + derived data first
#
# Flags combine, e.g.: ./scripts/dev-build.sh --clean --test

set -euo pipefail

ACTION="build"
CONFIG="Debug"
CLEAN="no"

while [ $# -gt 0 ]; do
    case "$1" in
        --open)    ACTION="open"; shift ;;
        --test)    ACTION="test"; shift ;;
        --install) ACTION="install"; CONFIG="Release"; shift ;;
        --release) CONFIG="Release"; shift ;;
        --debug)   CONFIG="Debug"; shift ;;
        --clean)   CLEAN="yes"; shift ;;
        -h|--help) sed -n '2,17p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *)         echo "Unknown option: $1" >&2; exit 2 ;;
    esac
done

cd "$(git rev-parse --show-toplevel)"

info() { printf '\033[1;34m==>\033[0m %s\n' "$1"; }
die()  { printf '\033[1;31mxx\033[0m  %s\n' "$1" >&2; exit 1; }

[ "$(uname -s)" = "Darwin" ] || die "ClaudeBar is a macOS app; this script needs a Mac."
command -v tuist >/dev/null 2>&1 || die "Tuist not found. Install it with: brew install --cask tuist"
command -v xcodebuild >/dev/null 2>&1 || die "xcodebuild not found. Install Xcode from the App Store."

DERIVED="$PWD/.build/derived"
WORKSPACE="ClaudeBar.xcworkspace"
DEST='platform=macOS,arch=arm64'

# --- Generate ---------------------------------------------------------------

if [ "$CLEAN" = "yes" ]; then
    info "Cleaning generated project and derived data"
    rm -rf "$DERIVED" ClaudeBar.xcodeproj ClaudeBar.xcworkspace Derived
    tuist clean >/dev/null 2>&1 || true
fi

info "Resolving dependencies (tuist install)"
tuist install

info "Generating Xcode project (tuist generate)"
tuist generate --no-open

# Workaround for tuist/tuist#9111 — CI runs this too; without it the build
# fails with "Unexpected duplicate tasks" on SwiftTerm's Shaders.metal.
./scripts/fix-swiftterm-metal.sh

if [ "$ACTION" = "open" ]; then
    info "Opening $WORKSPACE"
    open "$WORKSPACE"
    exit 0
fi

# --- Test -------------------------------------------------------------------

if [ "$ACTION" = "test" ]; then
    info "Running tests"
    xcodebuild test \
        -scheme ClaudeBar \
        -workspace "$WORKSPACE" \
        -destination "$DEST" \
        -derivedDataPath "$DERIVED" \
        -skipMacroValidation
    exit 0
fi

# --- Build ------------------------------------------------------------------

info "Building $CONFIG"
xcodebuild build \
    -scheme ClaudeBar \
    -workspace "$WORKSPACE" \
    -destination "$DEST" \
    -derivedDataPath "$DERIVED" \
    -configuration "$CONFIG"

APP="$DERIVED/Build/Products/$CONFIG/ClaudeBar.app"
[ -d "$APP" ] || die "Build reported success but $APP is missing."
info "Built $APP"

[ "$ACTION" = "install" ] || exit 0

# --- Install ----------------------------------------------------------------

# Stamp the bundle (not the repo) so your build is identifiable and so Sparkle
# doesn't quietly replace it with an official tddworks release. Patching the
# built .app instead of Sources/App/Info.plist keeps your diff against upstream
# empty here — Info.plist is rewritten on every upstream release.
UPSTREAM_VERSION="$(sed -n 's/^## \[\([0-9][^]]*\)\].*/\1/p' CHANGELOG.md | head -1)"
SHA="$(git rev-parse --short HEAD)"
STAMP="${UPSTREAM_VERSION:-0.0.0}-fork.$SHA"
PLIST="$APP/Contents/Info.plist"

/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $STAMP" "$PLIST"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(git rev-list --count HEAD)" "$PLIST"
/usr/libexec/PlistBuddy -c "Set :SUEnableAutomaticChecks false" "$PLIST" 2>/dev/null || true

# Re-sign ad-hoc: editing Info.plist invalidates the signature the build made.
codesign --force --deep --sign - "$APP"

if pgrep -x ClaudeBar >/dev/null 2>&1; then
    info "Quitting the running ClaudeBar"
    osascript -e 'quit app "ClaudeBar"' 2>/dev/null || pkill -x ClaudeBar || true
    sleep 2
fi

info "Installing to /Applications/ClaudeBar.app ($STAMP)"
rm -rf /Applications/ClaudeBar.app
ditto "$APP" /Applications/ClaudeBar.app
xattr -dr com.apple.quarantine /Applications/ClaudeBar.app 2>/dev/null || true

open -a /Applications/ClaudeBar.app
info "Installed and launched. Settings live in ~/.claudebar/settings.json"
