#!/usr/bin/env bash
# Shared by the post-merge / post-checkout hooks.
#
# The Xcode project is generated by Tuist and git-ignored, so when a sync brings
# in changes to Project.swift or Tuist/Package.swift, your local .xcworkspace is
# stale — targets, dependencies, or build settings no longer match the sources.
# The symptom is a confusing build failure right after a sync, so we call it out
# the moment it happens.
#
# Usage: tuist-drift-check.sh <old-rev> <new-rev>
#
# Set CLAUDEBAR_AUTO_GENERATE=1 to regenerate automatically instead of warning.

set -euo pipefail

OLD="${1:-}"
NEW="${2:-}"
[ -n "$OLD" ] && [ -n "$NEW" ] || exit 0
[ "$OLD" != "$NEW" ] || exit 0

WATCHED=(Project.swift Tuist/Package.swift Tuist.swift)

changed="$(git diff --name-only "$OLD" "$NEW" -- "${WATCHED[@]}" 2>/dev/null || true)"
[ -n "$changed" ] || exit 0

# No generated workspace yet? Nothing has drifted — the first build will make it.
[ -e "$(git rev-parse --show-toplevel)/ClaudeBar.xcworkspace" ] || exit 0

if [ "${CLAUDEBAR_AUTO_GENERATE:-0}" = "1" ] && command -v tuist >/dev/null 2>&1; then
    printf '\033[1;34m==>\033[0m Tuist inputs changed — regenerating the Xcode project\n'
    cd "$(git rev-parse --show-toplevel)"
    tuist install && tuist generate --no-open && ./scripts/fix-swiftterm-metal.sh
    exit 0
fi

cat <<EOF

$(printf '\033[1;33m')┌──────────────────────────────────────────────────────────────┐
│ Tuist inputs changed — your Xcode project is stale.          │
└──────────────────────────────────────────────────────────────┘$(printf '\033[0m')

Changed:
$(echo "$changed" | sed 's/^/  /')

Regenerate before building:

    ./scripts/dev-build.sh --open

(Export CLAUDEBAR_AUTO_GENERATE=1 to have this hook do it automatically.)

EOF
